### ISSUE TITLE
PyMusic support for complex MPI Datatypes?

### ISSUE THREAD

**Issue by uahic** [INCF/MUSIC#18]
PyMusic supports auto detection of primitive datatypes of the buffer passed by the user. There are use cases where complex data types could also be desired as for example in NEST with the music_cont_out_proxy when observing multiple quantities at once to save additional proxies and function calls. 

@mdjurfeldt There are a few questions now: do you think its worth it to implement this support in the PyMusic interface? I put some thoughts in how to accomplish auto detection by the given buffer but I think the most straight forward solution would be to have a helper function that creates a proper numpy-dtype with an api like create_numpy_dtype( primitive_dtype, multiplicity) and possibly an alternative for a pure python array.

**Comment by apeyser** [comment]
On the nest end, all the music communications go directly through nest and are intermediated by python. So the question is whether there are interested users on the other end to make it worth the work in both pymusic and in nest.

**Comment by mdjurfeldt** [comment]
@uahic Can we keep things as simple as possible (no auto detection for now) until we have concrete use cases/needs in an actual application where we see that auto detection would make life easier?
