### ISSUE TITLE
Travis CL checks are failing

### ISSUE THREAD

**Issue by JanneM** [INCF/MUSIC#3]
Seem the Travis setup is failing for MUSIC. The tests fail already during setup:

$ sudo python get-pip.py

You're using an outdated location for the get-pip.py script, please use the one available from https://bootstrap.pypa.io/get-pip.py

The command "sudo python get-pip.py" failed and exited with 1 during .

Your build has been stopped.

**Comment by lekshmideepu** [comment]
I will correct it soon

**Comment by mdjurfeldt** [comment]
Thanks!

(I would have done it myself, but am busy until end of the week.)

**Comment by lekshmideepu** [comment]
Now there is a problem with one of the test suite
./testsuite/sanitytests/clocksource.cc

**Comment by lekshmideepu** [comment]
I have merged the changes since this was critical.
1. changed the download location of get-pip
2. using minimal image of trusty
3. installing python-all-dev

**Comment by mdjurfeldt** [comment]
Thanks!

Yes, the clock source test is a known problem.

Best regards,
Mikael
Den 1 feb 2016 13:25 skrev "lekshmideepu" notifications@github.com:
