### ISSUE TITLE
Virtual destructor for EventHandlerGlobalIndex missing?

### ISSUE THREAD

**Issue by uahic** [INCF/MUSIC#4]
Hi,

I just tried to compile Monsteer (which uses MUSIC) against the most recent MUSIC version but the compiler complains as follows:

> error: ‘class SpikesHandler’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]

In src/music/event.hh  it seems that a virtual destructor is missing (I just learned why its good to have one: http://stackoverflow.com/questions/5827719/class-has-virtual-functions-and-accessible-non-virtual-destructor)

Compiler: gcc 4.8.3

**Comment by mdjurfeldt** [comment]
This issue is now solved due to PR #7.
