### ISSUE TITLE
Compiling PyMusic without MPI?

### ISSUE THREAD

**Issue by sanjayankur31** [INCF/MUSIC#55]
Hello,

Is pymusic not meant to be used without MPI at all? I see that [configure.ac file has a conditional](https://github.com/INCF/MUSIC/blob/master/configure.ac#L330), and then the [pymusic Makefile](https://github.com/INCF/MUSIC/blob/master/pymusic/Makefile.am#L7) tries to run `python3 tests.py` which imports `mpi4py`?

Cheers!

**Comment by mdjurfeldt** [comment]
Hi Ankur,

The released version of MUSIC as well as the development version in this repository depends on MPI for its communication. Therefore, it would not make sense to use the MUSIC Python wrapper in the directory pymusic without MPI. This may change in a future version, though. Why are you asking?

**Comment by sanjayankur31** [comment]
Ah, that makes sense---I hadn't realised. 

I am packaging it for [NeuroFedora](https://fedoraproject.org/wiki/SIGs/NeuroFedora) (as I have done [NEST](https://src.fedoraproject.org/rpms/nest), and have [submitted libneurosim for review too](https://bugzilla.redhat.com/show_bug.cgi?id=1638968), so that I can then package up PyNN). I built both NEST and libneurosim with and without MPI support, and was following the same method for MUSIC too. 

If MUSIC needs MPI support, I will not build the non-MPI variant, and so I expect this means that MUSIC can only be used with NEST if NEST is built with MPI support?

**Comment by mdjurfeldt** [comment]
Yes, that is correct. The current version of MUSIC should be used together with MPI and an MPI-enabled NEST. Good luck with your work! Closing issue.

**Comment by sanjayankur31** [comment]
Great. Thanks for confirming.
