### ISSUE TITLE
Link to manual is broken

### ISSUE THREAD

**Issue by teonnik** [INCF/MUSIC#57]
The following link in the README: http://software.incf.org/software/music/home appears to be broken.

**Comment by apeyser** [comment]
Hi Teodor,

The current MUSIC repository is github:
https://github.com/INCF/MUSIC

It looks like the redirect is broken on incf.

I believe you can build the manual in the 'doc' subdirectory.

Regards,
Alex

-----Original Message-----

**Comment by mdjurfeldt** [comment]
Dear Teodor and Alex, the manual can now be found [here](https://github.com/INCF/MUSIC/wiki/files/music-manual.pdf).

I've updated the README.

Please submit new issues or contact me at mikael@djurfeldt.com if you have further questions.
