### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by Helloworld-Le** [INCF/MUSIC#59]
Hi，

I got this error after typing 'make install':

_Making install in mpidep
make[1]: Entering directory '/home/le/Installation/MUSIC/mpidep'
make[2]: Entering directory '/home/le/Installation/MUSIC/mpidep'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/le/Installation/MUSIC/mpidep'
make[1]: Leaving directory '/home/le/Installation/MUSIC/mpidep'
Making install in rudeconfig
make[1]: Entering directory '/home/le/Installation/MUSIC/rudeconfig'
make[2]: Entering directory '/home/le/Installation/MUSIC/rudeconfig'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/le/Installation/MUSIC/rudeconfig'
make[1]: Leaving directory '/home/le/Installation/MUSIC/rudeconfig'
Making install in src
make[1]: Entering directory '/home/le/Installation/MUSIC/src'
make[2]: Entering directory '/home/le/Installation/MUSIC/src'
/bin/mkdir -p '/usr/local/lib'
/bin/bash ../libtool   --mode=install /usr/bin/install -c   libmusic.la libmusic-c.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libmusic.so.1.0.0 /usr/local/lib/libmusic.so.1.0.0
/usr/bin/install: cannot remove '/usr/local/lib/libmusic.so.1.0.0': Permission denied
Makefile:533: recipe for target 'install-libLTLIBRARIES' failed
make[2]: *** [install-libLTLIBRARIES] Error 1
make[2]: Leaving directory '/home/le/Installation/MUSIC/src'
Makefile:1090: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/le/Installation/MUSIC/src'
Makefile:440: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1_

Then I used 'sudo make install', seems it was installed but when I run test files, it fails:

_mpirun -np 4 /usr/local/bin/music demo.music
/usr/local/bin/music: error while loading shared libraries: libmusic.so.1: cannot open shared object file: No such file or directory
/usr/local/bin/music: error while loading shared libraries: libmusic.so.1: cannot open shared object file: No such file or directory
/usr/local/bin/music: error while loading shared libraries: libmusic.so.1: cannot open shared object file: No such file or directory
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
/usr/local/bin/music: error while loading shared libraries: libmusic.so.1: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

Process name: [[4272,1],0]
Exit code:    127
--------------------------------------------------------------------------_

I have no idea how to solve this:(
best,
luke

**Comment by dizcza** [comment]
@Helloworld-Le maybe this will help you https://github.com/INCF/MUSIC/issues/58

**Comment by dizcza** [comment]
@Helloworld-Le try installing not system-wide as I explained here https://github.com/incf-music/music-adapters/issues/8#issuecomment-507988463.
But before that, make sure to remove libmusic*.so in `/usr/local/lib`. You can do this with `sudo make uninstall`
