### ISSUE TITLE
Errors in ../testsuite/sanitytests/clocksource.cc file

### ISSUE THREAD

**Issue by lekshmideepu** [INCF/MUSIC#6]
There are some syntax issues with "../testsuite/sanitytests/clocksource.cc" file

../../../testsuite/sanitytests/clocksource.cc: In function ‘int main(int, char*_)’:
../../../testsuite/sanitytests/clocksource.cc:107:3: error: ‘Setup’ is not a member of ‘MUSIC’
../../../testsuite/sanitytests/clocksource.cc:107:17: error: ‘setup’ was not declared in this scope
../../../testsuite/sanitytests/clocksource.cc:107:29: error: expected type-specifier
../../../testsuite/sanitytests/clocksource.cc:107:29: error: expected ‘;’
../../../testsuite/sanitytests/clocksource.cc:114:3: error: ‘ContOutputPort’ is not a member of ‘MUSIC’
../../../testsuite/sanitytests/clocksource.cc:114:26: error: ‘out’ was not declared in this scope
../../../testsuite/sanitytests/clocksource.cc:123:3: error: ‘ArrayData’ is not a member of ‘MUSIC’
../../../testsuite/sanitytests/clocksource.cc:123:20: error: expected ‘;’ before ‘dmap’
../../../testsuite/sanitytests/clocksource.cc:129:16: error: ‘dmap’ was not declared in this scope
../../../testsuite/sanitytests/clocksource.cc:131:16: error: ‘dmap’ was not declared in this scope
../../../testsuite/sanitytests/clocksource.cc:139:3: error: ‘Runtime’ is not a member of ‘MUSIC’
../../../testsuite/sanitytests/clocksource.cc:139:19: error: ‘runtime’ was not declared in this scope
../../../testsuite/sanitytests/clocksource.cc:139:33: error: expected type-specifier
../../../testsuite/sanitytests/clocksource.cc:139:33: error: expected ‘;’
../../../testsuite/sanitytests/clocksource.cc:150:10: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
   delete runtime;
          ^
make[3]: *_\* [clocksource-clocksource.o] Error 1

@Michael: I had already reported this issue last year. Could you please have a look at it?

**Comment by mdjurfeldt** [comment]
Fixed by commit a705c75.
