### ISSUE TITLE
Is version 1.17 ready now?

### ISSUE THREAD

**Issue by hosiet** [INCF/MUSIC#73]
I see that https://github.com/INCF/MUSIC/commit/521c3ed7ed871d98fe031b4857b59c78d970c613 updates package metadata to be version 1.17, but https://github.com/INCF/MUSIC/tags does not show anything about 1.17. Can I consider version 1.17 to be released? If so, please also add a git tag for this release. Thanks!

**Comment by mdjurfeldt** [comment]
Yes, please consider version 1.1.17 released (actually already December 8:th).

Thank you for pointing this out. I had forgotten to push tag 1.1.17 to github. This is fixed now, and I have also prepared a proper github "release".

Best regards,
Mikael
