### ISSUE TITLE
In Python 3.12, the distutils package is removed

### ISSUE THREAD

**Issue by musicinmybrain** [INCF/MUSIC#74]
In Python 3.12, the distutils package is removed: https://github.com/python/cpython/issues/92584

-----

Currently, you can still get `import distutils` by installing `setuptools`, so one workaround would be to simply document that `setuptools` is needed. I’ve confirmed that this is sufficient to make the [Fedora Linux package](https://src.fedoraproject.org/rpms/MUSIC) compatible with the Python 3.12.0a5 pre-release.

-----

Migrating from `distutils` to `setuptools` would also be pretty straightforward.

- In `configure.ac`, `from distutils import sysconfig` can become ~~`from setuptools import sysconfig`~~ `import sysconfig`.
- In `pymusic/setup.py.in`, `from distutils.core import setup` can become `from setuptools import setup`.
- In `pymusic-old/setup.py`, `from distutils.core import setup` and `from distutils.extension import Extension` can be replaced by `from setuptools import Extension, setup`.
- In `pymusic/pymusic.pyx` and `pymusic/pybuffer.pyx`, the `# distutils: language = c++` comments should still be correctly interpreted by Cython even without distutils.
- In `pymusic/tests.py`, the replacement of `distutils.version import LooseVersion` is a little less straightforward. The easiest thing to do would be to introduce a test dependency on `packaging`: https://packaging.pypa.io/en/stable/version.html

**Comment by hroncok** [comment]
Rather than `from setuptools import sysconfig`, I suggest using the `sysconfig` module from Python standard library. In the case of this configure.ac script, `distutils.sysconfig.get_python_inc()` can be replaced by `sysconfig.get_path('include')`.

**Comment by mdjurfeldt** [comment]
Many thanks!

This should now be fixed in commit d49d1a2e. I will create a new release + new Debian packages within a couple of days.

The directory pymusic-old remains there only for reference and is not used.
