### ISSUE TITLE
MUSIC Python extension and mpi4py 4

### ISSUE THREAD

**Issue by JCGoran** [INCF/MUSIC#80]
I've noticed that the latest version (4) of the mpi4py package is not compatible with the latest release of MUSIC (1.2.1 if I'm not mistaken). The write-up of the issue is available [here](https://github.com/neuronsimulator/nrn/issues/3095#issuecomment-2391128342). Note that version 3.x of mpi4py is compatible with MUSIC, however, with Python 3.13 just around the corner, and mpi4py 3.x [not being supported](https://github.com/mpi4py/mpi4py/issues/555) on that Python version (at least not without applying some workarounds), I am wondering if there is a plan for a version of MUSIC compatible with mpi4py version 4?

**Comment by mdjurfeldt** [comment]
I'll look into this and respond within a couple of days.

**Comment by bnhquang** [comment]
Hi guys, is this already fixed and will be closed soon? Just looking around for possibility of contribution
